### PR TITLE
Search 5K limit fix

### PR DESCRIPTION
**Pull request by Chris-Schnaufer**
This builds off PR https://github.com/CulverLab/sparcd/pull/40.

Updates some dependencies for building to newer versions
Closing query after all records have been fetched

### CODE REVIEW

**Comment by julianpistorius** [comment]
@Chris-Schnaufer is this PR ready to be merged?

**Comment by Chris-Schnaufer** [comment]
> @Chris-Schnaufer is this PR ready to be merged?

Yes, both this and #40 are available for merging. This builds off PR 40, so you may want to merge that one first

**Comment by julianpistorius** [comment]
@Chris-Schnaufer it looks like #41 (this PR) has three commits ahead of the commits for #40, followed by some more commits. See the commits in the red rectangle below - the commits in the green rectangles are the ones they have in common:

---

## PR 41 commits

mr-41-commits

## PR 40 commits

mr-40-commits

**Comment by julianpistorius** [comment]
I am struggling to build and test the older version of the app now that I've upgraded it to Java 15, so I will test the upload retry behavior in #41 instead of in #40.

**Comment by Chris-Schnaufer** [comment]
> I am struggling to build and test the older version of the app now that I've upgraded it to Java 15, so I will test the upload retry behavior in #41 instead of in #40.

Do you need anything from me?

**Comment by julianpistorius** [comment]
> Do you need anything from me?

Nope. I got it working. Thanks!

**Pull request merged**
